version: '3.4'

services:
  asterisk_callcenter_ami_monitoring:
    container_name: asterisk_callcenter_ami_monitoring
    build: .
    env_file: .env
    restart: always
    volumes:
      - ./app/:/app
    network_mode: host
